#https://github.com/Microsoft/GSL/blob/master/.travis.yml


branches:
  except:
  - /dev-appveyor.+/
  - /doc.+/

language: cpp
os: linux
dist: bionic
git:
  depth: 15

matrix:
  include:
    - compiler: clang
    - compiler: gcc

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
    # Use Debug builds for collecting coverage
  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug
    # Don't bother with release build for coverage build
  - cmake -H. -BBuild-Release -DCMAKE_BUILD_TYPE=Release


script:
  - cd Build-Debug
  - cmake --build .
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
    # Go to release build
  - cd ../Build-Release
  - cmake --build .
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
